name: Deploy Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        env:
          CI: true
        run: npm install
      - name: Build the plugin
        run: npm run build:all
      - name: Deploy Demo 🚀 https://kevinchappell.github.io/formBuilder/
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: demo
